/*
Copyright (C) 2023-2026 QuantumNous

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

For commercial licensing, please contact support@quantumnous.com
*/
package model

import (
	"encoding/json"
	"errors"
	"fmt"
	"math/rand"
	"strings"
	"sync"

	"github.com/QuantumNous/new-api/common"
	"github.com/QuantumNous/new-api/constant"
	"github.com/QuantumNous/new-api/relaykit/dto"
	"github.com/QuantumNous/new-api/relaykit/types"
	"gorm.io/gorm"
)

// Account 账户实体：凭证与渠道解耦。凭证类字段（key / base_url / 代理 / 多key状态 /
// 编码套餐 / 余额）以账户为唯一真相源，渠道通过 account_id 引用；多渠道可共享同一
// 账户（同厂商同 key 复用、多 key 轮询状态跨渠道共享、余额只查一次）。
//
// 渠道表的同名列（key/base_url/setting/channel_info/coding_plan_*/balance…）保留为
// legacy 只读降级列：account_id=0（历史数据未 backfill / 挂载失败）时访问器回退渠道列。
// Type 为厂商权威来源；channels.type 是反规范化副本（列表过滤/渠道测试仍按渠道列，
// 换绑/换类型时由 controller 同步收敛，见 SyncChannelTypeFromAccount）。
type Account struct {
	Id                 int     `json:"id"`
	Name               string  `json:"name" gorm:"index"`
	Type               int     `json:"type" gorm:"default:0"`
	Status             int     `json:"status" gorm:"default:1"`
	Key                string  `json:"-" gorm:"not null"` // 永不下发；响应经 KeyMasked 脱敏预览
	KeyMasked          string  `json:"key_masked" gorm:"-"`
	Other              string  `json:"other"`
	BaseURL            *string `json:"base_url" gorm:"column:base_url;default:''"`
	Setting            *string `json:"setting" gorm:"type:text"`        // 代理等（原渠道 Setting）
	Balance            float64 `json:"balance"`                         // in USD
	OtherInfo          string  `json:"other_info" gorm:"type:text"`     // status_reason/status_time（自动启停滞回）
	OtherSettings      string  `json:"settings" gorm:"column:settings"` // Azure 版本等（原渠道 OtherSettings，AdvancedCustom 留渠道覆盖）
	Remark             *string `json:"remark" gorm:"type:varchar(255)" validate:"max=255"`
	CreatedTime        int64   `json:"created_time" gorm:"bigint"`
	BalanceUpdatedTime int64   `json:"balance_updated_time" gorm:"bigint"`
	OpenAIOrganization *string `json:"openai_organization"`

	// 多key状态（轮询索引/各 key 启停）随凭证走，跨渠道共享。
	ChannelInfo ChannelInfo `json:"channel_info" gorm:"type:json"`

	// 编码套餐余量监控（原渠道 CodingPlan* 字段账户化：套餐账号跟凭证走）。
	CodingPlanProvider   *string `json:"coding_plan_provider" gorm:"size:32"`
	CodingPlanKey        string  `json:"-" gorm:"size:512"`               // 套餐专用密钥，永不下发
	CodingPlanKeyMasked  string  `json:"coding_plan_key_masked" gorm:"-"` // 响应脱敏预览
	CodingPlanQuotaGroup string  `json:"coding_plan_quota_group,omitempty" gorm:"-"`

	// 编码套餐自动启停：组级语义天然归一（共享账户的渠道一起禁用/恢复）。
	// *bool/*int 与渠道侧同理由：允许 GORM Updates(struct) 写入零值关闭。
	CodingPlanAutoControl      *bool `json:"coding_plan_auto_control"`
	CodingPlanDisableThreshold *int  `json:"coding_plan_disable_threshold"`
	CodingPlanEnableThreshold  *int  `json:"coding_plan_enable_threshold"`

	UpdatedAt int64 `json:"updated_at" gorm:"autoUpdateTime"`

	// AutoGenerated 标记系统生成的账户（存量渠道 backfill / 新建渠道未显式选账户时
	// 自动创建）。删除渠道后的孤儿清理只回收此类账户；用户手动创建的账户即使无渠道
	// 引用也保留（可能是预留待绑定的）。不用 gorm default 标签（AGENTS 规则），
	// 创建路径显式赋值。
	AutoGenerated bool `json:"auto_generated"`
}

func (Account) TableName() string { return "accounts" }

// ── key 解析/轮询（自 Channel 平移，状态源换成账户自身） ─────────────

// GetKeys 解析账户 key 列表：JSON 数组（Vertex AI 场景）或换行分隔。
func (account *Account) GetKeys() []string {
	if account.Key == "" {
		return []string{}
	}
	trimmed := strings.TrimSpace(account.Key)
	if strings.HasPrefix(trimmed, "[") {
		if arr, ok := parseKeyJSONArray(trimmed); ok {
			return arr
		}
	}
	return strings.Split(strings.Trim(account.Key, "\n"), "\n")
}

// parseKeyJSONArray 解析 JSON 数组格式的 key 列表（Vertex AI 多密钥对象）。
func parseKeyJSONArray(raw string) ([]string, bool) {
	var arr []json.RawMessage
	if err := common.Unmarshal([]byte(raw), &arr); err != nil {
		return nil, false
	}
	res := make([]string, len(arr))
	for i, v := range arr {
		res[i] = string(v)
	}
	return res, true
}

// GetNextEnabledKey 按 ChannelInfo.MultiKeyMode 返回一个可用 key。
// 多渠道共享同一账户（缓存路径共享 *Account 指针 / DB 路径每次新查），轮询索引与
// key 启停状态都在 account.ChannelInfo 上，锁按账户 id——共享账户的并发轮询安全。
func (account *Account) GetNextEnabledKey() (string, int, *types.NewAPIError) {
	if !account.ChannelInfo.IsMultiKey {
		return account.Key, 0, nil
	}
	keys := account.GetKeys()
	if len(keys) == 0 {
		return "", 0, types.NewError(errors.New("no keys available"), types.ErrorCodeChannelNoAvailableKey)
	}

	lock := GetAccountPollingLock(account.Id)
	lock.Lock()
	defer lock.Unlock()

	statusList := account.ChannelInfo.MultiKeyStatusList
	getStatus := func(idx int) int {
		if statusList == nil {
			return common.ChannelStatusEnabled
		}
		if status, ok := statusList[idx]; ok {
			return status
		}
		return common.ChannelStatusEnabled
	}

	enabledIdx := make([]int, 0, len(keys))
	for i := range keys {
		if getStatus(i) == common.ChannelStatusEnabled {
			enabledIdx = append(enabledIdx, i)
		}
	}
	if len(enabledIdx) == 0 {
		return "", 0, types.NewError(errors.New("no enabled keys"), types.ErrorCodeChannelNoAvailableKey)
	}

	switch account.ChannelInfo.MultiKeyMode {
	case constant.MultiKeyModeRandom:
		selectedIdx := enabledIdx[rand.Intn(len(enabledIdx))]
		return keys[selectedIdx], selectedIdx, nil
	case constant.MultiKeyModePolling:
		defer func() {
			// DB 路径（非内存缓存）把轮询索引落库；缓存路径共享指针即时可见。
			if !common.MemoryCacheEnabled {
				_ = account.SaveChannelInfo()
			}
		}()
		start := account.ChannelInfo.MultiKeyPollingIndex
		if start < 0 || start >= len(keys) {
			start = 0
		}
		for i := 0; i < len(keys); i++ {
			idx := (start + i) % len(keys)
			if getStatus(idx) == common.ChannelStatusEnabled {
				account.ChannelInfo.MultiKeyPollingIndex = (idx + 1) % len(keys)
				return keys[idx], idx, nil
			}
		}
		return keys[enabledIdx[0]], enabledIdx[0], nil
	default:
		return keys[enabledIdx[0]], enabledIdx[0], nil
	}
}

// SaveChannelInfo 持久化账户多 key 状态（轮询索引/启停）。
func (account *Account) SaveChannelInfo() error {
	return DB.Model(account).Update("channel_info", account.ChannelInfo).Error
}

// UpdateBalance 更新账户余额（余额归账户，多渠道共享一份）。
func (account *Account) UpdateBalance(balance float64) {
	err := DB.Model(account).Select("balance_updated_time", "balance").Updates(Account{
		BalanceUpdatedTime: common.GetTimestamp(),
		Balance:            balance,
	}).Error
	if err != nil {
		common.SysLog(fmt.Sprintf("failed to update account balance: account_id=%d, error=%v", account.Id, err))
	}
}

// GetSetting 解析账户级代理等设置（与 Channel.GetSetting 同构）。
func (account *Account) GetSetting() dto.ChannelSettings {
	setting := dto.ChannelSettings{}
	if account.Setting != nil && *account.Setting != "" {
		if err := common.Unmarshal([]byte(*account.Setting), &setting); err != nil {
			common.SysLog(fmt.Sprintf("failed to unmarshal account setting: account_id=%d, error=%v", account.Id, err))
			account.Setting = nil
			_ = DB.Model(account).Select("setting").Update("setting", nil).Error
		}
	}
	return setting
}

// SetSetting 序列化并写入账户设置列。
func (account *Account) SetSetting(setting dto.ChannelSettings) {
	settingBytes, err := common.Marshal(setting)
	if err != nil {
		common.SysLog(fmt.Sprintf("failed to marshal account setting: account_id=%d, error=%v", account.Id, err))
		return
	}
	account.Setting = common.GetPointer[string](string(settingBytes))
}

// GetOtherInfo / SetOtherInfo 与 Channel 同构（status_reason 等自动启停滞回状态）。
func (account *Account) GetOtherInfo() map[string]interface{} {
	otherInfo := make(map[string]interface{})
	if account.OtherInfo != "" {
		if err := common.Unmarshal([]byte(account.OtherInfo), &otherInfo); err != nil {
			common.SysLog(fmt.Sprintf("failed to unmarshal account other info: account_id=%d, error=%v", account.Id, err))
		}
	}
	return otherInfo
}

func (account *Account) SetOtherInfo(otherInfo map[string]interface{}) {
	otherInfoBytes, err := common.Marshal(otherInfo)
	if err != nil {
		common.SysLog(fmt.Sprintf("failed to marshal account other info: account_id=%d, error=%v", account.Id, err))
		return
	}
	account.OtherInfo = string(otherInfoBytes)
}

// SaveStatusState 只落状态流字段（status/other_info + 多key 状态），防止过期快照
// 覆盖凭证。与 Channel.saveStatusState 同构；导出供套餐自动启停任务（service 层）
// 写账户滞回状态。
func (account *Account) SaveStatusState() error {
	if account.Id == 0 {
		return errors.New("account ID is 0")
	}
	updates := map[string]any{
		"status":     account.Status,
		"other_info": account.OtherInfo,
	}
	if account.ChannelInfo.IsMultiKey {
		updates["channel_info"] = account.ChannelInfo
	}
	return DB.Model(&Account{}).Where("id = ?", account.Id).Updates(updates).Error
}

// ── 账户轮询锁（按账户 id；共享账户跨渠道并发轮询安全） ─────────────

var accountPollingLocks sync.Map

// GetAccountPollingLock 返回/创建账户级轮询锁。
func GetAccountPollingLock(accountId int) *sync.Mutex {
	if lock, exists := accountPollingLocks.Load(accountId); exists {
		return lock.(*sync.Mutex)
	}
	newLock := &sync.Mutex{}
	actual, _ := accountPollingLocks.LoadOrStore(accountId, newLock)
	return actual.(*sync.Mutex)
}

// ── CRUD ─────────────────────────────────────────────────────────

func (account *Account) Insert() error {
	return DB.Create(account).Error
}

// Update 全量字段更新（Updates(struct) 跳过零值，凭证清空需 Select 显式列）。
func (account *Account) Update() error {
	return DB.Model(account).Updates(account).Error
}

func (account *Account) Save() error {
	return DB.Save(account).Error
}

// Delete 删除账户：仍有渠道引用时拒绝（先解绑/删除渠道）。引用关系以绑定表为准。
func (account *Account) Delete() error {
	count, err := CountChannelsBoundToAccount(account.Id)
	if err != nil {
		return err
	}
	if count > 0 {
		return fmt.Errorf("账户仍被 %d 个渠道引用，请先删除或解绑相关渠道", count)
	}
	return DB.Delete(account).Error
}

// GetAccountById 查单个账户；selectAll=false 时 Omit key（列表/详情脱敏路径）。
func GetAccountById(id int, selectAll bool) (*Account, error) {
	account := &Account{Id: id}
	var err error
	if selectAll {
		err = DB.First(account, "id = ?", id).Error
	} else {
		err = DB.Omit("key", "coding_plan_key").First(account, "id = ?", id).Error
	}
	if err != nil {
		return nil, err
	}
	return account, nil
}

// maskAccountSecrets 用已加载的明文算出脱敏预览（列表这类只读路径用）。
// 注意：不要在这里清掉 Key 本身——controller 的 fillAccountView 还会用同一份
// 明文再算一次预览，清早了会把 key_masked 覆盖成空串。明文不会下发：
// Account.Key / CodingPlanKey 的 json 标签都是 "-"。
func maskAccountSecrets(accounts []*Account) {
	for _, account := range accounts {
		account.KeyMasked = maskAccountKeyPreview(account.Key)
		if account.CodingPlanKey != "" {
			account.CodingPlanKeyMasked = maskAccountKeyPreview(account.CodingPlanKey)
		}
	}
}

// GetAllAccounts 分页列表（脱敏），按 id 倒序。

func GetAllAccounts(startIdx int, num int) ([]*Account, error) {
	var accounts []*Account
	err := DB.Order("id desc").Limit(num).Offset(startIdx).Find(&accounts).Error
	maskAccountSecrets(accounts)
	return accounts, err
}

// SearchAccounts 关键字搜索（id/name/base_url），脱敏。
func SearchAccounts(keyword string) ([]*Account, error) {
	var accounts []*Account
	baseURLCol := "`base_url`"
	if common.UsingMainDatabase(common.DatabaseTypePostgreSQL) {
		baseURLCol = `"base_url"`
	}
	err := DB.
		Where("id = ? OR name LIKE ? OR "+baseURLCol+" LIKE ?",
			common.String2Int(keyword), "%"+keyword+"%", "%"+keyword+"%").
		Order("id desc").Find(&accounts).Error
	maskAccountSecrets(accounts)
	return accounts, err
}

// AccountListFilter 账户列表的过滤条件；零值表示该项不限。
type AccountListFilter struct {
	Keyword    string
	Type       int
	Status     int
	Referenced *bool // nil = 不限：被渠道引用的 / 没被引用的
	Monitoring *bool // nil = 不限：开了套餐余量监控的 / 没开的
}

// applyAccountListFilter 把过滤条件落到查询上（列表与计数共用同一份条件，口径必须一致）。
func applyAccountListFilter(q *gorm.DB, f AccountListFilter) *gorm.DB {
	if f.Keyword != "" {
		baseURLCol := "`base_url`"
		if common.UsingMainDatabase(common.DatabaseTypePostgreSQL) {
			baseURLCol = `"base_url"`
		}
		q = q.Where("id = ? OR name LIKE ? OR "+baseURLCol+" LIKE ?",
			common.String2Int(f.Keyword), "%"+f.Keyword+"%", "%"+f.Keyword+"%")
	}
	if f.Type > 0 {
		q = q.Where("type = ?", f.Type)
	}
	if f.Status > 0 {
		q = q.Where("status = ?", f.Status)
	}
	if f.Monitoring != nil {
		// 与前端口径一致：显式配了厂商才算开启监控，空串 / "none" 都算关闭。
		if *f.Monitoring {
			q = q.Where("coding_plan_provider IS NOT NULL AND coding_plan_provider NOT IN ('', 'none')")
		} else {
			q = q.Where("coding_plan_provider IS NULL OR coding_plan_provider IN ('', 'none')")
		}
	}
	if f.Referenced != nil {
		sub := "SELECT DISTINCT account_id FROM channel_accounts"
		if *f.Referenced {
			q = q.Where("id IN (" + sub + ")")
		} else {
			q = q.Where("id NOT IN (" + sub + ")")
		}
	}
	return q
}

// GetAccountsFiltered 过滤 + 分页查询（脱敏：不返回 key / coding_plan_key）。
func GetAccountsFiltered(startIdx int, num int, f AccountListFilter) ([]*Account, error) {
	var accounts []*Account
	err := applyAccountListFilter(DB.Model(&Account{}), f).
		Order("id desc").Limit(num).Offset(startIdx).Find(&accounts).Error
	maskAccountSecrets(accounts)
	return accounts, err
}

// CountAccountsFiltered 与列表同一口径的计数（分页 total）。
func CountAccountsFiltered(f AccountListFilter) (int64, error) {
	var total int64
	err := applyAccountListFilter(DB.Model(&Account{}), f).Count(&total).Error
	return total, err
}

// AccountFacets 账户列表筛选下拉需要的计数。
type AccountFacets struct {
	Type       map[int]int64 `json:"type"`
	Status     map[int]int64 `json:"status"`
	Referenced int64         `json:"referenced"`
	Monitoring int64         `json:"monitoring"`
}

// GetAccountFacets 汇总各筛选项的计数（账户表很小，逐项 GROUP BY 足够）。
func GetAccountFacets() (AccountFacets, error) {
	facets := AccountFacets{Type: map[int]int64{}, Status: map[int]int64{}}
	type countRow struct {
		Value int
		Count int64
	}
	var rows []countRow
	if err := DB.Model(&Account{}).Select("type AS value, count(*) AS count").
		Group("type").Scan(&rows).Error; err != nil {
		return facets, err
	}
	for _, row := range rows {
		facets.Type[row.Value] = row.Count
	}
	rows = nil
	if err := DB.Model(&Account{}).Select("status AS value, count(*) AS count").
		Group("status").Scan(&rows).Error; err != nil {
		return facets, err
	}
	for _, row := range rows {
		facets.Status[row.Value] = row.Count
	}
	refCounts, err := CountChannelAccountReferences()
	if err != nil {
		return facets, err
	}
	facets.Referenced = int64(len(refCounts))
	if err := DB.Model(&Account{}).
		Where("coding_plan_provider IS NOT NULL AND coding_plan_provider NOT IN ('', 'none')").
		Count(&facets.Monitoring).Error; err != nil {
		return facets, err
	}
	return facets, nil
}

// CountAllAccounts 账户总数（分页用）。
func CountAllAccounts() (int64, error) {
	var total int64
	err := DB.Model(&Account{}).Count(&total).Error
	return total, err
}

// GetAccountsByIds 批量查账户（含 key，供渠道挂载路径使用）。
func GetAccountsByIds(ids []int) ([]*Account, error) {
	if len(ids) == 0 {
		return nil, nil
	}
	var accounts []*Account
	err := DB.Where("id in (?)", ids).Find(&accounts).Error
	return accounts, err
}

// CountChannelsByAccountId 统计引用某账户的渠道数（走绑定表：账户 N:N 后
// channels.account_id 不再是真相源）。
func CountChannelsByAccountId(accountId int) (int64, error) {
	return CountChannelsBoundToAccount(accountId)
}

// CountChannelAccountReferences 一次 GROUP BY 统计各账户引用渠道数（列表页用，走绑定表）。
func CountChannelAccountReferences() (map[int]int64, error) {
	return CountChannelAccountBindingMap()
}

// ChannelRefView 账户被引用渠道的摘要（列表页"被哪些渠道引用"展示用）。
type ChannelRefView struct {
	Id     int    `json:"id"`
	Name   string `json:"name"`
	Status int    `json:"status"`
}

// ListChannelRefsByAccount 一次查出所有账户的引用渠道摘要（列表页用，走绑定表）。
func ListChannelRefsByAccount() (map[int][]ChannelRefView, error) {
	type refRow struct {
		AccountId int
		Id        int
		Name      string
		Status    int
	}
	var rows []refRow
	err := DB.Table("channel_accounts AS ca").
		Select("ca.account_id AS account_id, ch.id AS id, ch.name AS name, ch.status AS status").
		Joins("JOIN channels AS ch ON ch.id = ca.channel_id").
		Order("ca.account_id ASC, ca.account_order ASC, ca.id ASC").
		Scan(&rows).Error
	if err != nil {
		return nil, err
	}
	out := make(map[int][]ChannelRefView)
	for _, r := range rows {
		out[r.AccountId] = append(out[r.AccountId], ChannelRefView{
			Id: r.Id, Name: r.Name, Status: r.Status,
		})
	}
	return out, nil
}

// GetChannelsByAccount 查询引用某账户的渠道（换绑/删除确认视图、类型同步），走绑定表。
func GetChannelsByAccount(accountId int) ([]*Channel, error) {
	return GetChannelsBoundToAccount(accountId)
}

// SyncChannelsTypeByAccount 账户换类型后同步所有引用渠道的 channels.type（反规范化
// 副本：base_url 默认值/适配器选择/type_counts 统计都按渠道列），并逐渠道重建
// abilities。事务内执行；完成后由调用方刷新渠道缓存。
func SyncChannelsTypeByAccount(accountId int, newType int) error {
	return DB.Transaction(func(tx *gorm.DB) error {
		boundChannelIds := tx.Model(&ChannelAccount{}).Select("channel_id").Where("account_id = ?", accountId)
		if err := tx.Model(&Channel{}).Where("id IN (?)", boundChannelIds).Update("type", newType).Error; err != nil {
			return err
		}
		var channels []*Channel
		if err := tx.Where("id IN (?)", boundChannelIds).Find(&channels).Error; err != nil {
			return err
		}
		for _, ch := range channels {
			ch.Type = newType
			if err := ch.UpdateAbilities(tx); err != nil {
				return err
			}
		}
		return nil
	})
}

// CleanupOrphanPrivateAccounts 删除无渠道引用的孤儿账户。只回收系统自动生成
// （AutoGenerated）的账户；用户手动创建的账户即使暂无引用也保留（可能预留待绑定）。
// 删除渠道/批量删除/解绑后调用。
func CleanupOrphanPrivateAccounts() (int64, error) {
	var orphans []int
	if err := DB.Model(&Account{}).
		// 只认"指向仍然存在的渠道"的绑定：渠道被批量删除（不逐个走 Channel.Delete）时
		// 绑定行可能残留，这里按 join 判活，避免孤儿账户永远收不回来。
		Where("auto_generated = "+commonTrueVal+
			" AND id NOT IN (SELECT ca.account_id FROM channel_accounts ca JOIN channels c ON c.id = ca.channel_id)").
		Pluck("id", &orphans).Error; err != nil {
		return 0, err
	}
	if len(orphans) == 0 {
		return 0, nil
	}
	result := DB.Where("id in (?)", orphans).Delete(&Account{})
	return result.RowsAffected, result.Error
}
