/*
Copyright (C) 2023-2026 QuantumNous

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

For commercial licensing, please contact support@quantumnous.com
*/
package model

import (
	"testing"

	"github.com/QuantumNous/new-api/common"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func setupAccountTestDB(t *testing.T) {
	t.Helper()
	require.NoError(t, DB.AutoMigrate(&Account{}, &Channel{}, &Ability{}, &ChannelModelSetting{}))
	require.NoError(t, DB.Where("1 = 1").Delete(&Channel{}).Error)
	require.NoError(t, DB.Where("1 = 1").Delete(&Account{}).Error)
	require.NoError(t, DB.Where("1 = 1").Delete(&Ability{}).Error)
	require.NoError(t, DB.Where("1 = 1").Delete(&ChannelModelSetting{}).Error)
}

// TestChannelAccountBackfillIdempotentAndComplete 保护存量渠道 backfill 的核心契约：
// 每个未挂账户的渠道生成私有账户（凭证字段一一搬运），且幂等（重跑不重复生成）。
func TestChannelAccountBackfillIdempotentAndComplete(t *testing.T) {
	setupAccountTestDB(t)

	provider := "zhipu"
	autoControl := true
	ch := &Channel{
		Type:          1,
		Name:          "backfill-source",
		Key:           "sk-legacy-key",
		Models:        "gpt-4o",
		Group:         "default",
		Status:        common.ChannelStatusEnabled,
		Balance:       12.5,
		CodingPlanProvider:   &provider,
		CodingPlanKey:        "cp-key",
		CodingPlanAutoControl: &autoControl,
	}
	ch.ChannelInfo.IsMultiKey = true
	ch.ChannelInfo.MultiKeyMode = "polling"
	ch.ChannelInfo.MultiKeySize = 2
	require.NoError(t, DB.Create(ch).Error)

	require.NoError(t, ensureChannelAccountBackfill(DB))

	var accounts []Account
	require.NoError(t, DB.Find(&accounts).Error)
	require.Len(t, accounts, 1, "每渠道应生成恰好一个私有账户")
	acc := accounts[0]
	assert.True(t, acc.AutoGenerated, "backfill 账户应标记 AutoGenerated")
	assert.Equal(t, ch.Key, acc.Key, "key 应搬运")
	assert.Equal(t, ch.Type, acc.Type, "type 应搬运")
	assert.Equal(t, ch.Balance, acc.Balance, "余额应搬运")
	assert.Equal(t, ch.CodingPlanProvider, acc.CodingPlanProvider, "套餐厂商应搬运")
	assert.Equal(t, ch.CodingPlanKey, acc.CodingPlanKey, "套餐密钥应搬运")
	assert.True(t, acc.ChannelInfo.IsMultiKey, "多 key 状态应搬运")
	assert.Equal(t, ch.CodingPlanAutoControl, acc.CodingPlanAutoControl, "自动启停配置应搬运")

	// 渠道已绑定
	var bound Channel
	require.NoError(t, DB.First(&bound, ch.Id).Error)
	assert.Equal(t, acc.Id, bound.AccountId)

	// 幂等：重跑不再生成新账户
	require.NoError(t, ensureChannelAccountBackfill(DB))
	var count int64
	require.NoError(t, DB.Model(&Account{}).Count(&count).Error)
	assert.Equal(t, int64(1), count)
}

// TestChannelDelegationToAccount 保护委托层契约：挂账户的渠道凭证读写全部走账户，
// 账户换 key 后所有引用渠道立即生效（无需改渠道行）。
func TestChannelDelegationToAccount(t *testing.T) {
	setupAccountTestDB(t)

	acc := &Account{Type: 1, Name: "shared-acc", Key: "sk-account-key", Status: common.ChannelStatusEnabled}
	require.NoError(t, DB.Create(acc).Error)

	chA := &Channel{Type: 1, Name: "ch-a", AccountId: acc.Id, Models: "gpt-4o", Group: "default", Status: common.ChannelStatusEnabled}
	chB := &Channel{Type: 1, Name: "ch-b", AccountId: acc.Id, Models: "gpt-4o", Group: "default", Status: common.ChannelStatusEnabled}
	require.NoError(t, DB.Create(chA).Error)
	require.NoError(t, DB.Create(chB).Error)

	require.NoError(t, chA.loadAccount())
	require.NoError(t, chB.loadAccount())

	// 非 multi-key：取 key 走账户
	key, _, apiErr := chA.GetNextEnabledKey()
	require.Nil(t, apiErr)
	assert.Equal(t, "sk-account-key", key)

	// 账户换 key 落库后，重新挂载的渠道立即拿到新 key（凭证唯一真相源）。
	chA.Account.Key = "sk-rotated"
	require.NoError(t, chA.Account.Save())
	require.NoError(t, chB.loadAccount())
	assert.Equal(t, []string{"sk-rotated"}, chB.GetKeys())
	key2, _, apiErr2 := chB.GetNextEnabledKey()
	require.Nil(t, apiErr2)
	assert.Equal(t, "sk-rotated", key2)

	// GetBaseURL：账户配置优先于厂商默认
	baseURL := "https://relay.example.com"
	chB.Account.BaseURL = &baseURL
	assert.Equal(t, baseURL, chB.GetBaseURL())
}

// TestSharedAccountPollingIndexCrossChannel 保护共享账户多 key 轮询契约：
// 轮询索引在账户上，共享账户的多渠道拿到的是连续且不重复的 key 序列
//（单渠道内轮询语义不变，跨渠道接力轮询）。
func TestSharedAccountPollingIndexCrossChannel(t *testing.T) {
	setupAccountTestDB(t)

	acc := &Account{Type: 1, Name: "polling-acc", Key: "k1\nk2\nk3", Status: common.ChannelStatusEnabled}
	acc.ChannelInfo.IsMultiKey = true
	acc.ChannelInfo.MultiKeyMode = "polling"
	acc.ChannelInfo.MultiKeySize = 3
	require.NoError(t, DB.Create(acc).Error)

	chA := &Channel{Type: 1, Name: "poll-ch-a", AccountId: acc.Id, Models: "gpt-4o", Group: "default", Status: common.ChannelStatusEnabled}
	chB := &Channel{Type: 1, Name: "poll-ch-b", AccountId: acc.Id, Models: "gpt-4o", Group: "default", Status: common.ChannelStatusEnabled}
	require.NoError(t, DB.Create(chA).Error)
	require.NoError(t, DB.Create(chB).Error)

	// 共享同一账户指针（模拟缓存路径的共享挂载）
	require.NoError(t, loadChannelsAccounts([]*Channel{chA, chB}))
	require.Same(t, chA.Account, chB.Account, "共享账户的渠道应持有同一账户指针")

	keyA1, _, errA := chA.GetNextEnabledKey()
	keyB1, _, errB := chB.GetNextEnabledKey()
	require.Nil(t, errA)
	require.Nil(t, errB)
	assert.NotEqual(t, keyA1, keyB1, "轮询索引共享：两渠道应拿到不同 key")
}

// TestAccountDeleteReferencedRejectedAndOrphanCleanup 保护删除契约：
// 有引用的账户删除被拒；孤儿清理只回收系统生成账户，手建账户保留。
func TestAccountDeleteReferencedRejectedAndOrphanCleanup(t *testing.T) {
	setupAccountTestDB(t)

	acc := &Account{Type: 1, Name: "referenced", Key: "sk-x", Status: common.ChannelStatusEnabled, AutoGenerated: true}
	require.NoError(t, DB.Create(acc).Error)
	ch := &Channel{Type: 1, Name: "bound", AccountId: acc.Id, Models: "gpt-4o", Group: "default", Status: common.ChannelStatusEnabled}
	require.NoError(t, DB.Create(ch).Error)

	err := acc.Delete()
	require.Error(t, err, "被引用账户删除应被拒绝")

	// 手建的无引用账户：清理时保留
	manual := &Account{Type: 1, Name: "manual", Key: "sk-m", Status: common.ChannelStatusEnabled}
	require.NoError(t, DB.Create(manual).Error)

	cleaned, err := CleanupOrphanPrivateAccounts()
	require.NoError(t, err)
	assert.Equal(t, int64(0), cleaned, "无孤儿 AutoGenerated 账户时应清理 0 个")

	// 删除引用渠道后：AutoGenerated 账户成孤儿被回收，手建账户保留
	require.NoError(t, DB.Delete(&Channel{}, ch.Id).Error)
	cleaned, err = CleanupOrphanPrivateAccounts()
	require.NoError(t, err)
	assert.Equal(t, int64(1), cleaned)

	var remaining []Account
	require.NoError(t, DB.Find(&remaining).Error)
	require.Len(t, remaining, 1)
	assert.Equal(t, "manual", remaining[0].Name, "手建账户不应被孤儿清理回收")
}

// TestBatchInsertChannelsCreatesPrivateAccount 保护创建路径契约：
// 未显式绑定账户的渠道在批量插入时自动生成私有账户并绑定。
func TestBatchInsertChannelsCreatesPrivateAccount(t *testing.T) {
	setupAccountTestDB(t)

	channels := []Channel{
		{Type: 1, Name: "auto-acc-1", Key: "sk-1", Models: "gpt-4o", Group: "default", Status: common.ChannelStatusEnabled},
		{Type: 1, Name: "auto-acc-2", Key: "sk-2", Models: "gpt-4o", Group: "default", Status: common.ChannelStatusEnabled},
	}
	require.NoError(t, BatchInsertChannels(channels))

	var accounts []Account
	require.NoError(t, DB.Find(&accounts).Error)
	require.Len(t, accounts, 2, "每渠道应自动生成私有账户")

	for _, acc := range accounts {
		assert.True(t, acc.AutoGenerated)
	}
	var bound []Channel
	require.NoError(t, DB.Find(&bound).Error)
	require.Len(t, bound, 2)
	for _, ch := range bound {
		assert.NotZero(t, ch.AccountId, "渠道应绑定自动生成的账户")
	}
}
