/*
Copyright (C) 2023-2026 QuantumNous

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

For commercial licensing, please contact support@quantumnous.com
*/
package model

import (
	"fmt"

	"github.com/QuantumNous/new-api/common"
	"gorm.io/gorm"
)

// SchemaMigration 记录已应用的 schema 迁移版本。启动时若已应用版本达到
// CurrentSchemaVersion 就跳过 AutoMigrate 与迁移，避免 SQLite（glebarez 驱动）
// 每次启动整表重建，也为旧库升级提供按版本的特殊适配通道。
type SchemaMigration struct {
	Version   int    `gorm:"primaryKey"`
	Name      string `gorm:"type:varchar(128)"`
	AppliedAt int64  `gorm:"autoCreateTime"`
}

func (SchemaMigration) TableName() string { return "schema_migrations" }

// CurrentSchemaVersion 是当前代码期望的 schema 版本。修改任何 model 结构时
// 必须递增该值；如需数据转换/特殊适配，同时新增对应的 Migration 条目。
// 兜底：DEBUG=true 启动时即使已最新也强制 AutoMigrate 校验结构。
// v5：users 表新增 space_capacity 列 + 新增 playground_conversations 表。
// v6：users 表新增 space_purchased_bytes 列（累计购买量）。
// v7：新增 playground_space_orders 表（云空间在线支付订单）。
// v8：users 表新增 credit_score 列 + 新增 credit_score_logs / conversation_records /
// credit_marker_suggestions / credit_marker_analysis_logs 表（AutoMigrate 建）。
// v9：credit_marker_analysis_logs 新增 retried 列（分析遇 429/5xx 自动重试的次数审计）。
// v10：credit_marker_suggestions 新增 log_ids 列（AI 建议关联的来源错误日志 id 集合）。
// v11：credit_marker_analysis_logs 新增 prompt_used 列（本次运行用的默认/自定义提示词标识）。
// v12：credit_score_logs 新增 reverted_at 列（管理端打回误判扣分的标记，补列见
// ensureCreditScoreLogReverted）。
// v13：user_subscriptions 新增 renew_terms 列（续费条款快照，续费走旧条款）。列由
// AutoMigrate 添加，无需数据转换——存量订阅无快照，续费/估值回退到套餐当前条款。
// v14：redemptions 新增 type（用途：1=兑换额度/2=注册邀请）、max_uses（可用次数）、
// used_count（已用次数）三列（AutoMigrate 加，带常量默认值）。存量码需保持一次性
// 语义，此处防御性 backfill：任何 NULL 统一归一为 type=1 / max_uses=1 / used_count=0。
// 同属 v14：新增 redemption_uses 关联表（redemption_id + user_id 唯一），保证同一
// 用户不能重复兑换同一码。表由 AutoMigrate（升版本路径）或 ensureRedemptionUsesTable
// （已最新版本库的跳过路径）创建，无需数据转换——存量已用码 status=3 仍由状态门控。
// 同属 v14：users 新增 activated 列（激活制：1=正式 / 0=待激活）。存量用户一律视为
// 已激活（default:1 回填），此处防御性 backfill 归一任何残余 NULL。列由 AutoMigrate
// 或 ensureUserActivatedColumn（已最新版本库的跳过路径）补建。
// v15：subscription_plans 新增 reset_windows 列、user_subscriptions 新增 window_state 列
// （动态重置窗口模型：多级独立额度窗口，订阅相对刷新；窗口 ≥ 有效期为封顶上限）。
// 列由 AutoMigrate（user_subscriptions）/SQLite 手工 DDL 或 ensure*（subscription_plans）
// 添加，无需数据转换——存量套餐 reset_windows 为空走 legacy 路径。
// v16：移除 legacy 订阅配额模型（计划 total_amount/quota_reset_*/reset_amount_limit/
// weekly/monthly_amount_limit 六列 + 订阅 cycle_start_at/cycle_used/next_cycle_reset_at 三列）。
// 删列由 ensureDropLegacySubscriptionPlanColumns / ensureDropLegacyUserSubscriptionColumns
// 幂等执行（挂在 migrateDB 两条分支，每次启动自检）；此处只打版本戳记录 schema 变更。
// v17：新增 channel_model_settings 表（渠道内模型级禁用 + 渠道级 context_window 覆盖，
// 只写非默认值行）+ models.context_window 列（模型级上下文窗口）。表/列由 AutoMigrate
// （升版本路径）或 ensureChannelModelSettingsTable / ensureModelsContextWindowColumn
// （已最新版本库的跳过路径）创建，无需数据转换——无行 = 启用 + 继承模型默认。
// v18：新增 accounts 表（凭证与渠道解耦：key/base_url/代理/多key状态/编码套餐/余额
// 归账户）+ channels.account_id 列。表/列由 AutoMigrate（升版本路径）或
// ensureAccountsTable / ensureChannelAccountIdColumn（已最新版本库的跳过路径）创建；
// 数据迁移 ensureChannelAccountBackfill 幂等执行：存量渠道（account_id=0）每渠道生成
// 私有账户（凭证字段一一搬运，AutoGenerated=true），渠道 legacy 凭证列保留只读降级。
const CurrentSchemaVersion = 18

// Migration 是一个可单独应用、记录版本戳的迁移步骤。Up 按版本升序执行，
// 用于 AutoMigrate 补不了的结构改造（换类型、删列）与数据迁移/特殊适配。
type Migration struct {
	Version int
	Name    string
	Up      func(db *gorm.DB) error
}

// migrations 按版本升序排列。v1 为版本化改造的基线：吸收此前 migrateDB 中
// AutoMigrate 之外的全部专项迁移与初始化逻辑（见 migrationBaselineV1）。
// v2 为订阅功能重设计：清空四张订阅表（AutoMigrate 已先把表结构升级到新版），
// 一次性破坏性操作，之后不再执行。
var migrations = []Migration{
	{Version: 1, Name: "baseline-2026-08", Up: migrationBaselineV1},
	{Version: 2, Name: "subscription-redesign-wipe", Up: migrationSubscriptionWipe},
	// v3: users 表新增 LinuxDO token 三列。列本身由 AutoMigrate 添加（本迁移在其后
	// 执行），此条目只打版本戳，避免每次启动 SQLite 整表重建。空 Up 表明无需数据
	// 转换：旧用户无 token，下次 LinuxDO 登录时写入。
	{Version: 3, Name: "linuxdo-token-columns", Up: func(db *gorm.DB) error { return nil }},
	// v4（图床表）/v5（users.space_capacity + playground 表/列）/v6（users.space_purchased_bytes）
	// 同理只打版本戳：表/列由 AutoMigrate 创建，无需数据转换；把版本推进到
	// CurrentSchemaVersion 让 shouldSkipMigration 生效，避免每次启动重复全量 AutoMigrate
	//（SQLite 整表重建风险）。
	{Version: 4, Name: "image-asset-table-noop", Up: func(db *gorm.DB) error { return nil }},
	{Version: 5, Name: "playground-space-noop", Up: func(db *gorm.DB) error { return nil }},
	{Version: 6, Name: "user-space-purchased-noop", Up: func(db *gorm.DB) error { return nil }},
	// v7：新增 playground_space_orders 表（AutoMigrate 建）+ 存量 users.space_purchased_bytes
	// 置 0。v6 新列无默认值，存量行是 NULL，累计上限条件 NULL + x 恒假导致拒买，这里统一回填。
	// 顺带把同属 v5 新增、同样无默认值的 space_capacity 的 NULL 一并置 0，归一化存量态。
	// Unscoped：Model(&User{}) 默认自动附加 deleted_at IS NULL，会把被软删除的行跳过，
	// 导致其 space 字段保持 NULL，恢复后仍触发拒买。Unscoped 去掉该过滤，覆盖全部行。
	// 幂等：跑过版本戳后不再执行。
	{Version: 7, Name: "user-space-purchased-backfill", Up: func(db *gorm.DB) error {
		if err := db.Unscoped().Model(&User{}).Where("space_purchased_bytes IS NULL").Update("space_purchased_bytes", 0).Error; err != nil {
			return err
		}
		return db.Unscoped().Model(&User{}).Where("space_capacity IS NULL").Update("space_capacity", 0).Error
	}},
	// v8：users.credit_score 列由 AutoMigrate 添加（带 default:650，存量行在
	// ALTER 时已回填 650）。此处防御性兜底：任何残余 NULL 统一置 650（满分）。
	// 同时 Unscoped 补 space 残留：早期 v7（未加 Unscoped）跑过的库，被软删除行的
	// space 字段仍是 NULL，这里一并归一，恢复后不再拒买。credit_score 同理——
	// 软删除行若残留 NULL，恢复后 Go 读作 0，会直接被信誉分冻结。
	// 幂等，跑过版本戳后不再执行。
	{Version: 8, Name: "user-null-backfill", Up: func(db *gorm.DB) error {
		if err := db.Unscoped().Model(&User{}).Where("space_purchased_bytes IS NULL").Update("space_purchased_bytes", 0).Error; err != nil {
			return err
		}
		if err := db.Unscoped().Model(&User{}).Where("space_capacity IS NULL").Update("space_capacity", 0).Error; err != nil {
			return err
		}
		return db.Unscoped().Model(&User{}).Where("credit_score IS NULL").Update("credit_score", 650).Error
	}},
	// v9：credit_marker_analysis_logs.retried 列由 AutoMigrate（新库/升版本路径）或
	// ensureCreditMarkerAnalysisLogRetried（已最新版本库的跳过路径）补列，无需数据转换；
	// 只打版本戳推进 shouldSkipMigration。
	{Version: 9, Name: "credit-marker-analysis-log-retried", Up: func(db *gorm.DB) error { return nil }},
	// v10：credit_marker_suggestions.log_ids 列同理（补列见 ensureCreditMarkerSuggestionLogIds）。
	{Version: 10, Name: "credit-marker-suggestion-log-ids", Up: func(db *gorm.DB) error { return nil }},
	// v11：credit_marker_analysis_logs.prompt_used 列同理（补列见 ensureCreditMarkerAnalysisLogPromptUsed）。
	{Version: 11, Name: "credit-marker-analysis-log-prompt-used", Up: func(db *gorm.DB) error { return nil }},
	// v12：credit_score_logs.reverted_at 列由 AutoMigrate 添加；存量行该列是 NULL，
	// 归零（未打回）保证 reverted_at = 0 语义，列表接口读出 0。
	{Version: 12, Name: "credit-score-log-reverted", Up: func(db *gorm.DB) error {
		return db.Model(&CreditScoreLog{}).Where("reverted_at IS NULL").Update("reverted_at", 0).Error
	}},
	// v13：user_subscriptions.renew_terms 列由 AutoMigrate 添加，无需数据转换；只打
	// 版本戳推进 shouldSkipMigration，避免 SQLite 每次启动整表重建。
	{Version: 13, Name: "subscription-renew-terms", Up: func(db *gorm.DB) error { return nil }},
	// v14：redemptions.type/max_uses/used_count 列由 AutoMigrate 添加（带常量默认值，
	// 存量行 ALTER 时已回填）。此处防御性 backfill 覆盖软删除行与历史库手工加列的
	// 边角：NULL 归一为 type=1 / max_uses=1 / used_count=0，保持存量码一次性语义。
	// Unscoped：默认 scope 附 deleted_at IS NULL 会把软删除行滤掉，必须去掉。
	{Version: 14, Name: "redemption-type-maxuses-backfill", Up: func(db *gorm.DB) error {
		if err := db.Unscoped().Model(&Redemption{}).Where("type IS NULL").Update("type", common.RedemptionCodeTypeTopup).Error; err != nil {
			return err
		}
		if err := db.Unscoped().Model(&Redemption{}).Where("max_uses IS NULL").Update("max_uses", 1).Error; err != nil {
			return err
		}
		if err := db.Unscoped().Model(&Redemption{}).Where("used_count IS NULL").Update("used_count", 0).Error; err != nil {
			return err
		}
		// users.activated 列：存量用户一律视为已激活（1），归一任何残余 NULL。
		return db.Unscoped().Model(&User{}).Where("activated IS NULL").Update("activated", 1).Error
	}},
	// v15：subscription_plans.reset_windows / user_subscriptions.window_state 列由
	// AutoMigrate（user_subscriptions）或 SQLite 手工 DDL / ensure*（subscription_plans）
	// 添加，无需数据转换；只打版本戳推进 shouldSkipMigration，避免 SQLite 每次启动整表重建。
	{Version: 15, Name: "subscription-reset-windows", Up: func(db *gorm.DB) error { return nil }},
	// v16：移除 legacy 订阅配额模型（9 个 legacy 列）。删列由幂等 ensureDropLegacy* 在
	// migrateDB 两条分支每次启动自检执行（跨 SQLite/MySQL/PostgreSQL）；本条目只打版本戳。
	{Version: 16, Name: "subscription-remove-legacy-columns", Up: func(db *gorm.DB) error { return nil }},
	// v17：channel_model_settings 表 + models.context_window 列由 AutoMigrate（升版本路径）
	// 或 ensureChannelModelSettingsTable / ensureModelsContextWindowColumn（已最新版本库的
	// 跳过路径）创建，无需数据转换；只打版本戳推进 shouldSkipMigration。
	{Version: 17, Name: "channel-model-settings-context-window", Up: func(db *gorm.DB) error { return nil }},
	// v18：accounts 表 + channels.account_id 列由 AutoMigrate（升版本路径）或
	// ensureAccountsTable / ensureChannelAccountIdColumn（跳过路径）创建；存量渠道
	// backfill（每渠道生成私有账户）由 ensureChannelAccountBackfill 幂等执行（挂在
	// migrateDB 两条分支每次启动自检），本条目只打版本戳。
	{Version: 18, Name: "accounts-channel-decoupling", Up: func(db *gorm.DB) error { return nil }},
}

// ensureSchemaMigrationsTable 用纯 SQL 建版本表，避免对版本表自身跑 AutoMigrate。
func ensureSchemaMigrationsTable(db *gorm.DB) error {
	return db.Exec(`CREATE TABLE IF NOT EXISTS schema_migrations (
		version integer PRIMARY KEY,
		name varchar(128),
		applied_at bigint)`).Error
}

// appliedSchemaVersion 返回已应用的最大迁移版本，无记录时返回 0。
func appliedSchemaVersion(db *gorm.DB) (int, error) {
	var version int
	err := db.Model(&SchemaMigration{}).
		Select("COALESCE(MAX(version), 0)").
		Scan(&version).Error
	return version, err
}

// shouldSkipMigration 判断是否可跳过迁移：已到最新版本且非 DEBUG。
// DEBUG 模式不跳过，强制 AutoMigrate 校验结构，防止改 model 忘递增版本戳
// 导致生产结构不同步（DEBUG 主要用于开发环境）。
func shouldSkipMigration(applied int) bool {
	return applied >= CurrentSchemaVersion && !common.DebugEnabled
}

// applyPendingMigrations 依次执行 applied 之后的所有迁移并逐个打版本戳。
// 每个迁移在独立事务中执行:Up 与打戳同事务,Up 失败则整体回滚且不写戳,
// 下次启动会从该版本重新执行,杜绝"半迁移 + 已打戳"的不完整状态。
// 注意:MySQL 的 DDL 会隐式提交,事务只能保护数据操作(DML);SQLite 与
// PostgreSQL 支持事务性 DDL,回滚更彻底。数据转换类迁移仍应在 Up 内部
// 自行保证幂等。ms 参数便于测试注入;生产路径传入包级 migrations。
func applyPendingMigrations(db *gorm.DB, applied int, ms []Migration) error {
	for _, m := range ms {
		if m.Version <= applied {
			continue
		}
		err := db.Transaction(func(tx *gorm.DB) error {
			if err := m.Up(tx); err != nil {
				return err
			}
			return tx.Create(&SchemaMigration{Version: m.Version, Name: m.Name}).Error
		})
		if err != nil {
			return fmt.Errorf("schema migration %d (%s): %w", m.Version, m.Name, err)
		}
		common.SysLog(fmt.Sprintf("applied schema migration %d (%s)", m.Version, m.Name))
	}
	return nil
}

// migrationBaselineV1 是版本化改造的基线迁移，吸收此前 migrateDB 中 AutoMigrate
// 之外的全部专项迁移与初始化逻辑。所有子步骤幂等,统一使用传入的 db
// (由 applyPendingMigrations 在事务中执行),不再依赖全局 DB。
func migrationBaselineV1(db *gorm.DB) error {
	if err := migrateSubscriptionPlanPriceAmount(db); err != nil {
		return err
	}
	if err := migrateTokenModelLimitsToText(db); err != nil {
		return err
	}
	if err := InitializeUserAuthVersions(db); err != nil {
		return err
	}
	if err := InitializeExternalIdentityClaims(db); err != nil {
		return err
	}
	if err := ensureQuotaClaimRecordsClean(db); err != nil {
		return err
	}
	if err := ensureQuotaClaimLockSeeded(db); err != nil {
		return err
	}
	return ensureSubscriptionPlanRecommendedBackfill(db)
}

// migrationSubscriptionWipe 是订阅功能重设计的破坏性迁移：清空四张订阅表。
// AutoMigrate 已先于本迁移执行，表结构已升级到新版；这里 DELETE 清掉旧数据，
// 让用户重新配置套餐并重新分配。一次性执行，之后由 v2 版本戳防止重复。
func migrationSubscriptionWipe(db *gorm.DB) error {
	tables := []string{
		"subscription_pre_consume_records",
		"subscription_orders",
		"user_subscriptions",
		"subscription_plans",
	}
	for _, table := range tables {
		if err := db.Exec("DELETE FROM " + table).Error; err != nil {
			return fmt.Errorf("subscription redesign wipe %s: %w", table, err)
		}
	}
	common.SysLog("[WARN] 订阅功能重设计迁移已执行：清空了 subscription_plans / user_subscriptions / subscription_orders / subscription_pre_consume_records，请重新配置套餐并为用户分配")
	return nil
}
